# Generated by Django 4.1.1 on 2022-11-10 13:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weekendpost', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='like',
        ),
        migrations.AddField(
            model_name='commends',
            name='like',
            field=models.ManyToManyField(related_name='liked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
