# Generated by Django 4.1.1 on 2023-01-02 05:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weekendpost', '0003_remove_commends_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_like',
            field=models.ManyToManyField(related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
