# Generated by Django 4.1.1 on 2023-01-03 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weekendpost', '0005_likepost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='post_like',
        ),
        migrations.AddField(
            model_name='likepost',
            name='post_like',
            field=models.ManyToManyField(related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='likepost',
            name='liked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
