# Generated by Django 4.1.1 on 2023-01-03 07:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weekendpost', '0006_remove_posts_post_like_likepost_post_like_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_like',
            field=models.ManyToManyField(related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='LikePost',
        ),
    ]
