# Generated by Django 4.1.1 on 2023-01-10 17:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weekendpost', '0008_remove_posts_post_like_postlikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlikes',
            name='liked_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
