# Generated by Django 4.1.1 on 2023-01-10 17:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weekendpost', '0009_postlikes_liked_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_like',
            field=models.ManyToManyField(related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PostLikes',
        ),
    ]
